# Generated by Django 2.0.4 on 2018-05-07 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prmanage', '0003_auto_20180507_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetask',
            name='project_id',
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 19, 5, 23, 644569)),
        ),
    ]
