# Generated by Django 2.0.4 on 2018-05-07 16:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prmanage', '0004_auto_20180507_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='project_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employeetasks', to='prmanage.Project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 19, 7, 7, 187331)),
        ),
    ]
